<?php /** @var \Amasty\RecurringPayments\Block\Customer\Subscriptions $block */ ?>
<div class="amrec-subscriptions-notice">
    <?= $block->escapeHtml(__('Please mind that we do not store some of the subscription data (i.e., Trial Start Date,'
        . ' Trial End Date, etc). It’s being dynamically retrieved from the Worldline gateway where you made your'
        . ' initial payment. If you notice some sort of data discrepancy, simply try to refresh this page.')) ?>
</div>
<div data-bind="scope: 'amasty-recurring-subscriptions'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /** @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
